/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thevoxelbox_intrinsic_Intrinsic */

#ifndef _Included_com_thevoxelbox_intrinsic_Intrinsic
#define _Included_com_thevoxelbox_intrinsic_Intrinsic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thevoxelbox_intrinsic_Intrinsic
 * Method:    rdtsc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_thevoxelbox_intrinsic_Intrinsic_rdtsc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
